AWSTemplateFormatVersion: "2010-09-09"

Description: "Test empty bucket on stack deletion"

Parameters:

  Bucket:
    Type: String
    Description: |
      The bucket to empty when this stack is deleted

Resources:

  DeleteLifecycle:
    Type: Custom::DeleteObjects
    Properties:
      Enabled: true
      ServiceToken: !ImportValue DeleteObjectsFunctionArn
      BucketName: !Ref Bucket
      RoleArn: !GetAtt DeleteObjectsFunctionRole.Arn

  DeleteObjectsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !ImportValue DeleteObjectsFunctionExecutionRoleArn
            Condition:
              StringEquals:
                sts:ExternalId: !ImportValue DeleteObjectsFunction
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EmptyBucketPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${Bucket}"
                  - !Sub "arn:${AWS::Partition}:s3:::${Bucket}/*"
